baseurl: 'https://goldmann.pl/'
locale: en-us
title: Marek Goldmann
theme: natrium
services:
  disqus:
    shortname: goldmann
  rss:
    limit: 10
pagination:
  pagerSize: 10
taxonomies:
  category: categories
  tag: tags
permalinks:
  page: '/:slug/'
  blog: '/blog/:year/:month/:day/:slug/'
menu:
  main:
    - name: Socially
      url: /socially
      weight: -140
    - name: Musically
      url: /musically
      weight: -150
    - name: Technically
      url: /technically
      weight: -160
    - name: Blog
      url: /blog
      weight: -200
params:
  description: ''
  logo:
    url: 'https://www.gravatar.com/avatar/e00cc70beb20a4a77809fd95b6f75ff2'
    width: 50
    height: 50
    alt: Logo
markup:
  goldmark:
    renderer:
      # Posts embed raw HTML (tweets, asciinema, SoundCloud)
      unsafe: true
  highlight:
    style: native
