---
title: "Red Hat and IBM"
author: "Marek Goldmann"
date: 2019-07-10
categories: ["General"]
tags: ["blog", "personal", "redhat"]
draft: false
---

There we go -- the Red Hat--IBM merger is now complete:

++++
<blockquote class="twitter-tweet" data-lang="pl"><p lang="en" dir="ltr">As <a href="https://twitter.com/hashtag/RedHat?src=hash&amp;ref_src=twsrc%5Etfw">#RedHat</a>&#39;s acquisition by <a href="https://twitter.com/IBM?ref_src=twsrc%5Etfw">@IBM</a> closes, Red Hat will maintain independence and neutrality to give customers freedom, choice and flexibility. Get the news: <a href="https://t.co/ggZWYrT8ut">https://t.co/ggZWYrT8ut</a> <a href="https://t.co/rw6hdvrqv7">pic.twitter.com/rw6hdvrqv7</a></p>&mdash; Red Hat, Inc. (@RedHat) <a href="https://twitter.com/RedHat/status/1148570974637498368?ref_src=twsrc%5Etfw">9 lipca 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

This is a pretty big deal. And I'm *not* talking about money only.

== Red Hat -- a company as I know it

I'm a Red Hatter link:https://twitter.com/marekgoldmann/status/1123228238438961153[since over 10 years now].
I joined the company when it had just a little bit over 2k people. Now we have over 14k. Over all these years
I saw how we grow. And we grew _really_ fast. Especially in recent years.

Everyone will tell you that Red Hat is about culture and not about material assets. And we really feel it, it's
not just talk for the public. We have a sense of contribute to what Red Hat is now.

It's actually pretty hard to compare Red Hat with a _standard_(?) company. Red Hat is *unique*. Culture of
openness is visible everywhere, on each level. I can talk with my manager about everything, I can have debates
on technical (and not only!) aspects with anyone in the company, I'm #never asked to be silent#.

I can have different view on things than the company does. I was not very happy with such big growth. Maintaining
the sense of belonging to a family with such rapid growth is hard. But in the end I think we managed it pretty well.

I have big confidence in link:https://twitter.com/JWhitehurst[Jim's] decisions. If you haven't had chance to listen to Jim,
do it. There are many interviews out there.

So, *IBM*.

== Wait, what? IBM?

When I heard for the first time that IBM is going to buy Red Hat -- it was a shock to me and I wasn't pleased with it,
to say it politely. IBM is a very big company and its reputation is, well, not that nice. Everyone recognizes this
company for great things that were done in the past but currently the *blue light doesn't really shine that bright*.

Many Red Hatters had similar feeling to me. Management knew it exactly -- we made sure they know it. It's an
link:https://www.redhat.com/en/explore/the-open-organization-book[open organization] after all!

I can only imagine what questions our customers had. As company employees we had them too. Many of them. I'll not
describe what steps management took to explain to us the details of the merger, but they did a very good job, especially Jim.

== Life after merger

There we are. One day after the deal is closed. So, what exactly will change? #*Nothing*#. And I'm really confident
about it. You may ask why?

1. If IBM will do _bad things_ to Red Hat -- IBM will sink with it. As simple as this. It's not about size of the
company you buy, it's more about what value it gives and what are the customer expectations related to it. And
these are defined pretty clearly: Red Hat stays, we expect *growth*.
2. Paying such huge amount of money (this is the biggest deal in software industry so far) for something you want
to consume only would be very, very bad move. What would IBM get from it? Nothing.
3. The whole company, without any changes, is moved to IBM and will operate as distinct unit in the Hybrid Cloud
team. Literally nothing changes in *what* we do and more importantly *how* we do it.
4. link:https://twitter.com/JWhitehurst[Jim] and link:https://twitter.com/GinniRometty[Ginni] said numerous times
that Red Hat will not be touched. Maybe I'm a little bit old-fashioned, but I trust in words that were said.

== What is the deal about?

Have you thought #what did IBM really bought here#?

Products!::
    Not really, they can have it *for free*.
Customer base?::
    IBM's is bigger.
Maybe employees?::
    Oh, this is not easy. You cannot just buy Red Hatters. We are a very opinionated crowd, if something is
    not the _Red Hat way_ many people will just resign. So, no, not employees.
Buildings?::
    For $34 billions? These must be very expensive buildings... 

So *what* it is?

My feeling is that #IBM wants to work the _Red Hat way_#. What is Red Hat way? This is how we work,
collaborate, discuss. All default to open.

IBM *must and wants to change*. IBM wants to be seen again as the company that innovates. Red Hat is required
here, because IBM alone could not do it. You could try to do the process yourself, but it would take too much time,
especially with a company of this size and the process would not be that visible to customers either.

You could change CEO, sure, but it does not work always as expected. Although
link:https://twitter.com/marekgoldmann/status/1129289849524183040[there are exceptions].

== What's the future then?

It will be fine.

IBM just cannot afford to screw this. I'm confident that
link:https://twitter.com/JWhitehurst/status/1148574277777657857[Red Hat will stay Red Hat]. And who
knows -- maybe IBM will _become_ Red Hat.

I look forward to see what's next!

*P.S.* I owe you another blog post explaining why I was quiet for so long time. I _promise_ to write it shortly.