version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: git submodule init && git submodule update
      - run: sudo apt-get install asciidoctor
      - run: cd ~/bin && curl -L https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.tar.gz | tar xvz
      - run: hugo -v -d www
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - www
      # We don't care about presentations on CI
      - run: rm -rf www/presentations
      - store_artifacts:
          path: www
  deploy:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run: sudo apt-get update && sudo apt-get install rsync
      - attach_workspace:
          at: /tmp/workspace
      - run: ssh-keyscan -H $SYNC_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "00:82:0e:1d:0f:bb:ac:d5:b2:e5:92:e3:b8:fd:f5:75"
      - run:
          name: Deploy with rsync
          command: |
            rsync -va --delete /tmp/workspace/www $SYNC_USER@$SYNC_HOST:$SYNC_PATH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master