---
title: "Hello, I'm Marek"
author: "Marek Goldmann"
date: 2018-10-14
categories: ["General"]
tags: ["blog", personal]
draft: false
---

TL;DR; *I'm back!*

It took a while. We didn't see each other in long time. Probably too long. So, let me introduce myself again. #*I'm Marek*#. Since almost 10 years I work for the same company: https://www.redhat.com/en[Red Hat], in the https://www.redhat.com/en/topics/middleware[Middleware part of it].

Over that time I was working on various different technologies. Among other things it was: virtualization (KVM, IaaS), Fedora (RPM packaging), Cloud (OpenShift), Middleware (TorqueBox) and more.

If I would be tasked to select one technology that influenced my work the most -- #I would choose *containers*#. This topic is close to everything I do in the last few years in a row.

I touched (learned, used, you name it) different programming languages like: Ruby, Java, Groovy, Python and of course Bash.

I was not only a programmer. I spent numerous hours on meetings and kind of tried to be a team lead of a very small group of three people.

So, who am I really? You may think: full stack developer, but I don't necessarily like this name. DevOps? Maybe a little bit better. For sure I'm someone between a programmer, ops guy and team lead. It changes every day, depending on the tasks I need to do.

Exciting times really.

Recently all this experience started to sparkle in my head the idea of returning back to digital life outside of my company.

So, I tweeted this:

++++
<blockquote class="twitter-tweet" data-lang="pl"><p lang="en" dir="ltr">I&#39;m considering bringing my feed alive. Anyone interested in topics close to my current work? Something between containers, OpenShift, CI/CD, guidelines, workflows, Jenkins. With occasional beer photos. And poor jokes. <a href="https://t.co/UQnEhihlM0">pic.twitter.com/UQnEhihlM0</a></p>&mdash; Marek Goldmann (@marekgoldmann) <a href="https://twitter.com/marekgoldmann/status/1051116893589901313?ref_src=twsrc%5Etfw">13 października 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

It turned out that people are not against it.

So, #here I am#.

== And?

You can expect more blog posts, of course. I expect that my blog will receive mostly technical posts. Occasionally there may be posted some other things, but not very often really.

You probably already noticed that the website itself got a refresh. I replaced my http://awestruct.org/[current static site generator] with https://gohugo.io/[Hugo]. There are still a few things that must be tweaked and the implementation is not as clean as I would like it to be, but the most important goal is already achieved: to make the content more readable.

Besides this, I'm returning to https://twitter.com/marekgoldmann[my Twitter]. This will be a mix of topics related to my work and my personal life. For sure you can expect topics mentioned in my tweet above and adventures with my race car (which I hope to drive more often).

Hello!
